host: 0.0.0.0
port: 9091
log_level: debug
jwt_secret: random_secret_goes_here
default_redirection_url: https://example.com:8443/adminstatus
totp:
  issuer: authelia.com

authentication_backend:
  disable_reset_password: true
  refresh_interval: 1m
  ldap:
    url: ldap://openldap
    skip_verify: false
    base_dn: dc=example,dc=org
    username_attribute: uid
    user: cn=admin,dc=example,dc=org
    password: admin
    users_filter: (&({username_attribute}={input})(objectClass=account))
    groups_filter: (&(member={dn})(objectclass=groupOfNames))

access_control:
  default_policy: deny
  rules:
    - domain: webadmin.example.com
      subject:
        - "user:WebAdmin"
      policy: one_factor
    - domain: example.com
      policy: one_factor

session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 3600
  inactivity: 300
  domain: example.com

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /var/lib/authelia/db.sqlite3

notifier:
  filesystem:
    filename: /var/lib/authelia/notification.txt
