version: '2'
services:
  openldap:
    image: osixia/openldap
    environment:
      LDAP_ADMIN_PASSWORD: "admin"
  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_SERVER_PATH: "/phpldapadmin"
    ports:
      - "127.0.0.1:8000:80"
  authelia:
    image: authelia/authelia
    volumes:
      - ./configuration.yml:/etc/authelia/configuration.yml:ro
  adminstatus:
    build: adminstatus
  mockservice:
    build: mockservice
  nginx:
    build: nginx
    ports:
      - "443:443"
    volumes:
      - /etc/cert/star_ccm_sickkids_ca.crt:/etc/ssl/certs/cert.crt:ro
      - /etc/cert/star_ccm_sickkids_ca.key:/etc/ssl/private/cert.key:ro
