version: '2'
services:
  openldap:
    image: osixia/openldap:1.3.0
    environment:
      LDAP_ADMIN_PASSWORD: "admin"
    volumes:
      - ./openldap_config:/etc/ldap/slapd.d/
      - ./openldap_data:/var/lib/ldap/
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_SERVER_PATH: "/phpldapadmin"
    ports:
      - "127.0.0.1:8000:80"
  authelia:
    image: authelia/authelia:4.19.1
    volumes:
      - ./configuration.yml:/etc/authelia/configuration.yml:ro
  adminstatus:
    build: adminstatus
    volumes:
      - ./log_adminstatus:/var/log/
  nginx:
    build: nginx
    ports:
      - "443:443"
    volumes:
      - /etc/cert/star_ccm_sickkids_ca_fullchain.crt:/etc/ssl/certs/cert.crt:ro
      - /etc/cert/star_ccm_sickkids_ca.key:/etc/ssl/private/cert.key:ro
      - ./.htpasswd:/.htpasswd:ro

networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/16
