version: '2'
services:
  openldap:
    image: osixia/openldap
    environment:
      LDAP_ADMIN_PASSWORD: "admin"
  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_SERVER_PATH: "/phpldapadmin"
    ports:
      - "8080:80"
  authelia:
    image: authelia/authelia
    volumes:
      - ./configuration.yml:/etc/authelia/configuration.yml:ro
  adminstatus:
    build: adminstatus
  nginx:
    build: nginx
    ports:
      - "8443:443"
